services:
 mongo-group:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_group_data:/data/db
    
 mysql-wielrennen:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_wielrennen_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: 1234
    
 mysql-koers:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_koers_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: 1234
    
 group:
  depends_on:
    - mongo-group
  image: wielandvandebotermet/group69
  ports:
    - 8080:8080
  links:
    - mongo-group
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-group
   
 koers:
  depends_on:
    - mysql-koers
  image: wielandvandebotermet/koers
  ports:
    - 8082:8082
  links:
    - mysql-koers
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: 1234
   MYSQL_DB_HOST: mysql-koers
   MYSQL_DB_PORT: 3307

 wielrennen:
  depends_on:
    - koers
    - group
  image: wielandvandebotermet/wielrennen
  ports:
    - 8081:8081
  links:
    - koers
    - group
  environment:
   PRODUCT_SERVICE_BASEURL: group:8080
   INVENTORY_INFO_SERVICE_BASEURL: koers:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: 1234
   MYSQL_DB_HOST: mysql-wielrennen
   MYSQL_DB_PORT: 3306

 api-gateway:
   depends_on:
     - koers
     - group
     - wielrennen
   image: wielandvandebotermet/api-gateway2
   ports:
     - 8083:8083
   links:
     - koers
     - group
     - wielrennen
   environment:
     GROUP_BASEURL: group:8080
     KOERS_BASEURL: koers:8082
     WIELRENNEN_BASEURL: wielrennen:8081

volumes:
 mongodb_group_data:
 mysql_koers_data:
 mysql_wielrennen_data: