services:
 mongo-Group:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_Group_data:/data/db
    
 mysql-wielrennen:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_wielrennen_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-Koers:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_Koers_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 Group:
  depends_on:
    - mongo-products
  image: wieland/Group
  ports:
    - 8080:8080
  links:
    - mongo-products
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-products
   
 Koers:
  depends_on:
    - mysql-inventory
  image: wieland/Koers
  ports:
    - 8082:8082
  links:
    - mysql-inventory
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: 1234
   MYSQL_DB_HOST: mysql-inventory
   MYSQL_DB_PORT: 3307

 wielrennen:
  depends_on:
    - product-service
    - inventory-service
  image: wieland/wielrennen
  ports:
    - 8081:8081
  links:
    - product-service
    - inventory-service
  environment:
   PRODUCT_SERVICE_BASEURL: product-service:8080
   INVENTORY_INFO_SERVICE_BASEURL: inventory-service:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: 1234
   MYSQL_DB_HOST: mysql-order
   MYSQL_DB_PORT: 3306

volumes:
 mongodb_Group_data:
 mysql_Koers_data:
 mysql_wielrennen_data: