server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: group
          uri: http://${GROUP_BASEURL:localhost:8080}
          predicates:
            - Path=/group
            - Method=POST
          filters:
            - SetPath=/api/group
        - id: group-all
          uri: http://${GROUP_BASEURL:localhost:8080}
          predicates:
            - Path=/group-all
            - Method=GET
          filters:
            - SetPath=/api/group/all
        - id: group-delete
          uri: http://${GROUP_BASEURL:localhost:8080}
          predicates:
            - Path=/group-Delete/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/group/Delete/{id}
        - id: group-Edit
          uri: http://${GROUP_BASEURL:localhost:8080}
          predicates:
            - Path=/group-Edit/{id}
            - Method=PUT
          filters:
            - SetPath=/api/group/Edit/{id}

        - id: koers
          uri: http://${KOERS_BASEURL:localhost:8082}
          predicates:
            - Path=/koers
            - Method=POST
          filters:
            - SetPath=/api/koers
        - id: koers-all
          uri: http://${KOERS_BASEURL:localhost:8082}
          predicates:
            - Path=/koers-all
            - Method=GET
          filters:
            - SetPath=/api/koers/all
        - id: koers-delete
          uri: http://${KOERS_BASEURL:localhost:8082}
          predicates:
            - Path=/koers-Delete/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/koers/Delete/{id}
        - id: koers-Edit
          uri: http://${KOERS_BASEURL:localhost:8082}
          predicates:
            - Path=/koers-Edit/{id}
            - Method=PUT
          filters:
            - SetPath=/api/koers/Edit/{id}

        - id: wielrenner
          uri: http://${WIELRENNEN_BASEURL:localhost:8081}
          predicates:
            - Path=/wielrenner
            - Method=POST
          filters:
            - SetPath=/api/wielrenner
        - id: wielrenner-all
          uri: http://${WIELRENNEN_BASEURL:localhost:8081}
          predicates:
            - Path=/wielrenner-all
            - Method=GET
          filters:
            - SetPath=/api/wielrenner/all
        - id: wielrennen-delete
          uri: http://${WIELRENNEN_BASEURL:localhost:8081}
          predicates:
            - Path=/wielrenner-Delete/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/wielrenner/Delete/{id}
        - id: wielrenner-Edit
          uri: http://${WIELRENNEN_BASEURL:localhost:8081}
          predicates:
            - Path=/wielrenner-Edit/{id}
            - Method=PUT
          filters:
            - SetPath=/api/wielrenner/Edit/{id}